config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations',  }
  get '/splash' => 'splash#index'
  root 'splash#index'

  resources :alerts

  post '/alerts/:id/send' => 'alerts#send_mail', as: :send_alert

  get '/search' => 'search#index'
  get '/search/:id' => 'search#show'
  post '/search/follow' => 'search#follow'
  post '/search/unfollow' => 'search#unfollow'
  get '/search/bill/:id', to: 'search#bill', as: :search_bill

  get '/bills/:id', to: 'bills#show', as: :bills
  post '/bills/:id/follow' => 'bills#follow'
  post '/bills/:id/unfollow' => 'bills#unfollow'

end

app/models/alert/search.rb
class Alert::Search < Alert
  OS_FIELDS = 'bill_id,state,session,title,actions'.freeze

  def self.model_name
    Alert.model_name
  end

  def check
    if os_results.any? && results_have_changed?(query)
      return update_as_run(os_checksum(recent_actions))
    end
  end

  def url_name
    'search/'
  end

  def os_bill
    false
  end

  def os_ts_query
    parsed_query.merge(q: ts_query)
  end

  def ts_query
    q = parsed_query[:q]

    return if q.blank?
    return q if q =~ /[&\|]/

    tokens = q.split
    tokens.join(' & ')
  end

  def os_results
    @_os_results ||= begin
      OpenStates::Bill.where(os_ts_query.merge(per_page: 10, fields: OS_FIELDS))
    rescue Faraday::ClientError => error
      if error.to_s.match(/429/)
        # busy try again later
      else
        errored!
      end
      [] # either way return empty array
    end
  end

  def url_query
    '?' + parsed_query.to_query(:search)
  end

  def recent_actions
    actions = os_results.select { |bill| bill.actions.any? }.map do |bill|
      bill.actions.last.slice('action', 'date')
    end
    actions.sort_by { |a| [a['date'], a['action']] }.reverse
  end

  def results_have_changed?(_query)
    checksum != os_checksum(recent_actions)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include FormHelper
  include BillFinder

  def index
    return unless query.present?
    return unless query?

    @bills = OpenStates::Bill.where(query)
  end

  def show
    query
    @bills = [bill_details]
    render :index
  end

  def follow
    find_or_create_alert
    render json: @alert, status: 201
  end

  def unfollow
    find_and_delete_alert
    render json: @alert, status: 202
  end

  def bill
    @bill = bill_details
    render json: @bill.as_json.merge(url_id: @bill.url_id)
  end

  private

  def find_or_create_alert
    @alert = current_user.find_alert_for_search(search_params)
    @alert ||= current_user.create_alert_for_search(search_params)
  end

  def find_and_delete_alert
    @alert = current_user.find_alert_for_search(search_params)
    @alert.destroy! if @alert.present?
  end

  def search_params
    return {} unless params[:search]
    params.require(:search).permit(:q, :state, :page, :per_page)
  end

  def text_query
    return unless search_params[:q].present?
    return search_params[:q] if search_params[:q] =~ /[&\|]/

    search_params[:q].split.join(' & ')
  end

  def state_filter
    search_params[:state]
  end

  def page
    search_params[:page] || '1'
  end

  def per_page
    search_params[:per_page] || '10'
  end

  def query
    @query ||= build_query
  end

  def query?
    text_query.present? || state_filter.present?
  end

  def build_query
    query = {}
    query[:state] = state_filter if state_filter.present?
    query[:q] = text_query if text_query.present?
    query[:page] = page if page.present?
    query[:per_page] = per_page if per_page.present?
    query
  end
end

app/views/search/_actions.html.haml
- if current_user.following?(bill)
  %button.btn.btn-success.following{data: { bill_id: bill.url_id, bill_name: bill.bill_id, bill_description: bill.desc }}
    Following
- else
  %button.btn.btn-default.follow{data: { bill_id: bill.url_id, bill_name: bill.bill_id, bill_description: bill.desc }}
    Follow

app/views/search/_form.html.haml
= panel title: 'Bill Search', context: :primary do
  = simple_form_for(:search, url: search_path,
      html: { id: 'search-form', method: 'get', class: 'form-horizontal' },
      wrapper: :horizontal_form ) do |f|

    .panel-body
      = f.error_notification

      .form-inputs
        = f.input :q, autofocus: true, label: 'Keyword or issue', required: false,
            input_html: { value: @query[:q] }
        = f.input :state, collection: us_states,
            label: 'Filter by State', required: false,
            selected: @query[:state],
            include_blank: true,
            input_html: { style: 'width:auto' }

    .panel-footer
      .buttons
        = f.button :submit, 'Search', class: "btn-primary"
        = link_to 'Cancel', search_path, class: 'btn btn-default'
        %span.pull-right
          - if @query.present? && user_signed_in?
            - if current_user.following?(@query)
              %button#search-as-alert.btn.btn-success.following{onclick: 'return false'} Following search
            - else
              %button#search-as-alert.btn.btn-default.follow{onclick: 'return false'} Save as alert

- content_for :javascripts do
  :javascript
    $('#search-as-alert').each(function(idx) {
      LegAlerts.handleFollows($(this));
    });

app/views/search/_modal.html.haml
#bill-details-modal.modal.fade{tabindex: "-1", role: 'dialog'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
        %h3.modal-title bill id
      .modal-body
        .ajax-loader
          %span.glyphicon.glyphicon-refresh.right-spinner
        .title
          the title
        .activity
          %h4 Activity
          .actions
      .modal-footer
        %button.btn{"data-dismiss" => "modal", type: "button"} Close

app/views/search/_results.html.haml
%table.table

  - @bills.each do |bill|
    %tr
      %td.actions
        - if current_user
          = render partial: 'actions', locals: { bill: bill }
        - else
          .sign-in-no-action
            = link_to 'Sign in for alerts', new_user_session_path, class: 'btn btn-default'
      %td.result
        .bill_id
          = link_to bill.bill_id, search_bill_path(bill.url_id), remote: true,
              data: { toggle: 'modal', target: '#bill-details-modal' }
          &nbsp;
          &#183;
          &nbsp;
          %span.os-link
            %span.glyphicon.glyphicon-new-window
            = link_to 'View on OpenStates.org', bill.os_url, target: '_blank'
        .session
          = bill.state.upcase
          Session
          = bill.session
        .title
          = bill.title
        .updated_at
          Updated:
          = bill.updated_at

= render 'modal'

- content_for :javascripts do
  :javascript
    $('.actions button').each(function(idx) {
      LegAlerts.handleFollows($(this));
    });
    $('a[data-remote]').on('ajax:success', function(e, data, status, xhr) {
      LegAlerts.showBillDetails(data);
    });

app/views/search/index.html.haml
.container
  .row
    .search
      = render 'form'

      - if @bills.present?
        %h2 Results
        = render 'results'