config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations',  }
  get '/splash' => 'splash#index'
  root 'splash#index'

  resources :alerts

  post '/alerts/:id/send' => 'alerts#send_mail', as: :send_alert

  get '/search' => 'search#index'
  get '/search/:id' => 'search#show'
  post '/search/follow' => 'search#follow'
  post '/search/unfollow' => 'search#unfollow'
  get '/search/bill/:id', to: 'search#bill', as: :search_bill

  get '/bills/:id', to: 'bills#show', as: :bills
  post '/bills/:id/follow' => 'bills#follow'
  post '/bills/:id/unfollow' => 'bills#unfollow'

end

app/models/alert.rb
class Alert < ApplicationRecord
  self.inheritance_column = :alert_type

  enum status: { active: 'active', archived: 'archived', errored: 'errored' }

  belongs_to :user

  before_create :generate_uuid

  scope :search, -> { where(alert_type: 'Alert::Search') }
  scope :bill, -> { where(alert_type: 'Alert::Bill') }
  scope :recent, -> { order(created_at: 'desc') }
  scope :by_name, -> { order('LOWER(name)') }

  attr_accessor :payload_string

  def self.humanize_query(query)
    clauses = []
    query.each do |k, v|
      next unless v.present?
      label = k == 'q' ? '' : k
      op = k == 'q' ? '' : ':'
      clauses << "#{label}#{op}#{v}"
    end
    clauses.join(' AND ')
  end

  def self.prune_query(query)
    query.slice(:q, :state).reject { |k,v| v.blank? }
  end

  def url_name
    'alerts/'
  end

  def public_url
    "#{Rails.application.routes.url_helpers.root_url}#{url_name}#{url_query}"
  end

  def url_query
    uuid
  end

  def to_param
    uuid
  end

  def generate_uuid
    self.uuid ||= SecureRandom.uuid
  end

  def pretty_query
    query
  end

  def has_query?(possible_query)
    self.class.prune_query(parsed_query).to_json == possible_query.to_json
  end

  def parsed_query
    JSON.parse(query, symbolize_names: true)
  rescue # if alert was hand-edited it may not be valid JSON anymore
    { q: query.to_s }
  end

  def mark_as_sent
    update_columns(last_sent_at: Time.zone.now)
  end

  def os_checksum(os_payload)
    self.payload_string = os_payload.to_json
    checksum = Digest::SHA256.hexdigest self.payload_string
    Rails.cache.write("alert-#{id}-#{checksum}", self.payload_string)
    checksum
  end

  def checksum_short
    (checksum || 'nocheck')[0..7]
  end

  private

  def write_payload_diff(sum)
    old_key = "alert-#{id}-#{checksum}"
    new_key = "alert-#{id}-#{sum}"
    old_payload = Rails.cache.fetch(old_key) { "{}" } # empty hash if not found
    new_payload = self.payload_string
    diff = Hashdiff.diff(JSON.parse(old_payload), JSON.parse(new_payload))
    Rails.cache.write("alert-#{id}-#{sum}-diff", diff)
  end

  def update_as_run(sum)
    write_payload_diff(sum)
    update!(last_run_at: Time.zone.now, checksum: sum)
  end
end

app/models/alert/bill.rb
class Alert::Bill < Alert
  def self.model_name
    Alert.model_name
  end

  def url_name
    'bills'
  end

  def os_bill
    @_os_bill ||= begin
      bill_id = parsed_query[:os_bill_id]
      if bill_id.length == 11
        bill_id = new_bill_id
      end

      fail Faraday::ResourceNotFound, id unless bill_id

      OpenStates::Bill.try_find_by_os_bill_id(bill_id, user, Rails.logger)
    rescue Faraday::ResourceNotFound => err
      # if it no longer exists, deactivate the alert
      archived!
      false
    rescue Faraday::ClientError => err
      # non-200 response of some kind. Log it and move on.
      errored!
      false
    end
  end

  def new_bill_id
    bill_id = name
    return unless description && description.match(/^\[..\ .+?\]/)
    state = description.match(/^\[(..)/)[1]
    session = description.match(/^\[..\ (.+?)\]/)[1]
    Base64.urlsafe_encode64(sprintf("%s/%s/%s", state, session, bill_id))
  end

  def os_url
    os_bill.os_url + '#actions'
  end

  def check
    if bill_has_changed?(os_bill)
      return update_as_run(os_checksum(os_bill))
    end
  end

  private

  def url_query
    '/' + parsed_query[:os_bill_id]
  end

  def bill_has_changed?(bill)
    return unless bill
    return true unless checksum # we have not checked before
    return false if bill.action_dates[:last].blank?

    Rails.logger.debug("last action date: #{bill.action_dates[:last]}")

    # most recent dates isn't always "last"
    dates = bill.action_dates.values_at('first', 'last').sort

    last_date = dates.first

    DateTime.parse(last_date) > last_run_at
  end
end

app/models/alert/search.rb
class Alert::Search < Alert
  OS_FIELDS = 'bill_id,state,session,title,actions'.freeze

  def self.model_name
    Alert.model_name
  end

  def check
    if os_results.any? && results_have_changed?(query)
      return update_as_run(os_checksum(recent_actions))
    end
  end

  def url_name
    'search/'
  end

  def os_bill
    false
  end

  def os_ts_query
    parsed_query.merge(q: ts_query)
  end

  def ts_query
    q = parsed_query[:q]

    return if q.blank?
    return q if q =~ /[&\|]/

    tokens = q.split
    tokens.join(' & ')
  end

  def os_results
    @_os_results ||= begin
      OpenStates::Bill.where(os_ts_query.merge(per_page: 10, fields: OS_FIELDS))
    rescue Faraday::ClientError => error
      if error.to_s.match(/429/)
        # busy try again later
      else
        errored!
      end
      [] # either way return empty array
    end
  end

  def url_query
    '?' + parsed_query.to_query(:search)
  end

  def recent_actions
    actions = os_results.select { |bill| bill.actions.any? }.map do |bill|
      bill.actions.last.slice('action', 'date')
    end
    actions.sort_by { |a| [a['date'], a['action']] }.reverse
  end

  def results_have_changed?(_query)
    checksum != os_checksum(recent_actions)
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @alert = Alert.new
  end

  def create
    @alert = Alert.create(alert_params.merge(user: current_user))
    redirect_to alert
  end

  def show
    alert
  end

  def edit
    alert
  end

  def update
    alert.update!(alert_params)
    redirect_to alert
  end

  def destroy
    Alert.delete(alert.id) # avoid the generated where(alert_type: ...)
    flash[:notice] = "Deleted alert #{alert.name}"
    redirect_to alerts_path
  end

  def send_mail
    AlertMailer.user_alert(alert).deliver_later
    alert.mark_as_sent
    flash[:notice] = 'Email alert is on its way'
    redirect_to alert_path(alert)
  end

  private

  def alert_params
    params.require(:alert).permit(:name, :description, :query, :alert_type)
  end

  def alert
    @alert ||= Alert.find_by(uuid: params[:id])
  end
end

app/views/alerts/_form.html.haml
= panel title: 'Alert', context: :primary do
  = simple_form_for(@alert, html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, boolean: :horizontal_boolean } ) do |f|

    .panel-body
      = f.error_notification

      .form-inputs
        = f.input :name, required: true, autofocus: true
        = f.input :status, collection: Alert.statuses
        = f.input :description
        = f.input :query
        = f.input :alert_type, as: :hidden, input_html: { value: (@alert.alert_type || 'Alert::Search') }

    .panel-footer
      .buttons
        = f.button :submit, 'Save', class: "btn-primary"
        = link_to 'Cancel', alerts_path, class: 'btn btn-secondary'

app/views/alerts/edit.html.haml
.container
  .row
    = render 'form'

app/views/alerts/index.html.haml
.container
  .row

    = link_to 'Create new alert', new_alert_path, class: 'btn btn-primary'

    %h2 Your alerts

    %table.table.alerts
      %tr
        %th Name
        %th Description
        %th Status
        %th Checksum
        %th Last sent

      - current_user.alerts.by_name.each do |alert|
        %tr
          %td.name
            = link_to alert.name, alert
          %td.description
            = alert.description
          %td.status
            = alert.status
          %td.checksum
            = alert.checksum_short
          %td.last_sent
            = alert.last_sent_at

app/views/alerts/new.html.haml
.container
  .row
    = render 'form'

app/views/alerts/show.html.haml
.container
  .row
    .leg-alert
      %h2
        Alert:&nbsp;
        = link_to @alert.name.try(:html_safe), @alert.public_url

      %dl
        %dt Status
        %dd
          = @alert.status

        %dt Description
        %dd
          = @alert.description.try(:html_safe)

        %dt Query
        %dd
          = link_to @alert.query.try(:html_safe), @alert.public_url

        %dt Last checked
        %dd
          = @alert.last_run_at

        %dt Last sent
        %dd
          = @alert.last_sent_at

        %dt Checksum
        %dd
          = @alert.checksum_short

  .row

    = link_to 'Edit', edit_alert_path(@alert), class: 'btn btn-primary'
    = link_to 'Delete', alert_path(@alert), method: 'delete', class: 'btn btn-danger'
    = link_to 'Send test email', send_alert_path(@alert), class: 'btn btn-default', method: 'post'