config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations',  }
  get '/splash' => 'splash#index'
  root 'splash#index'

  resources :alerts

  post '/alerts/:id/send' => 'alerts#send_mail', as: :send_alert

  get '/search' => 'search#index'
  get '/search/:id' => 'search#show'
  post '/search/follow' => 'search#follow'
  post '/search/unfollow' => 'search#unfollow'
  get '/search/bill/:id', to: 'search#bill', as: :search_bill

  get '/bills/:id', to: 'bills#show', as: :bills
  post '/bills/:id/follow' => 'bills#follow'
  post '/bills/:id/unfollow' => 'bills#unfollow'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate

  before_action :store_current_location, unless: :devise_controller?

  def authenticate
    unless ENV['HTTP_AUTH_USERNAME'].blank? or ENV['HTTP_AUTH_PASSWORD'].blank?
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['HTTP_AUTH_USERNAME'] && password == ENV['HTTP_AUTH_PASSWORD']
      end
    end
  end

  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  private

  def store_current_location
    url = request.url
    store_location_for(:user, url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      # allow either standard rails flash category symbols...
      when :notice then "info"
      when :success then "success"
      when :alert then "warning"
      when :error then "danger"
      # ... or bootstrap class symbols
      when :info then "info"
      when :warning then "warning"
      when :danger then "danger"
      # and default to being alarming
      else "danger"
    end
  end

  def page_title
    @title || controller_name.gsub( /Controller/, "" ).humanize
  end

  def provider_title(provider)
    return 'Google' if provider.to_s == 'google_oauth2'
    return provider.to_s.titleize
  end
end

app/views/application/_account_dropdown.html.haml
%li.dropdown
  %a.dropdown-toggle{ "href" => "#", "data-toggle"=>"dropdown", "role" => "button", "aria-expanded"=>"false"}
    Account <span class="caret"></span>
  %ul.dropdown-menu
    - if user_signed_in?
      = link_to 'Profile', edit_user_registration_path
      = link_to 'Sign out', destroy_user_session_path, :method=>:delete
    - else
      / CONNECT
      = link_to 'Sign in', new_user_session_path

app/views/application/_chromeframe.html.haml
/[if lt IE 7 ]
  %p.chromeframe
    You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.

app/views/application/_flashes.html.haml
- if !flash.empty?
  .container#flash
    - flash.each do |key, value|
      = alert_box value, context: flash_class(key), dismissible: true

app/views/application/_footer.html.haml
%footer#footer
  .container
    .row
      .col-xs-6
        %span.footer-link
          = link_to 'Legislative Alerts', 'https://github.com/legalerts/'
        %span.footer-link
          = link_to 'OpenSearch', 'https://opensearch.org/'
      .col-xs-6.text-right
        %small.copyright
          Copyright &copy; #{ Date.today.year }

app/views/application/_head.html.haml
%head
  %meta{ :charset => 'utf-8' }/
  %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/

  = display_meta_tags :site => 'Legislative Alerts', :title => page_title, :reverse => true

  %meta{ :name => 'description', :content => '' }/
  %meta{ :name => 'viewport', :content => 'width=device-width' }/

  = render 'stylesheets'
  = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'
  = javascript_include_tag 'modernizr'

  = csrf_meta_tag

app/views/application/_header.html.haml
= navbar position: :static do
  = vertical do
    = link_to root_path do
      %span.glyphicon.glyphicon-home
      Home
  = horizontal do
    = nav class: 'navbar-right' do
      = link_to 'Alerts', alerts_path
      = link_to 'Search', search_path
      - if user_signed_in?
        = link_to edit_user_registration_path, class: 'avatar-link' do
          .avatar
            = image_tag current_user.avatar_url, alt: 'Profile', width: '50px'
        = link_to 'Sign out', destroy_user_session_path, :method=>:delete
      - else
        / CONNECT
        = link_to 'Sign in', new_user_session_path

app/views/application/_javascripts.html.haml
= javascript_include_tag 'application'

-#  Append your own using content_for :javascripts
= yield :javascripts

-# Google Analytics
- if !ENV['GOOGLE_ANALYTICS_SITE_ID'].blank?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '#{ ENV['GOOGLE_ANALYTICS_SITE_ID'] }', 'auto');
    ga('send', 'pageview');

app/views/application/_stylesheets.html.haml
= stylesheet_link_tag 'application', :media => nil

-# Append your own using content_for :stylesheets
= yield :stylesheets